// Mock function prototypes
//
// Generated by ../../test/makeMocks.php (18fd8a4277524e5893fe2ec1a6f3fec2)
//
#ifndef _test_mockedFunctions_h_
#define _test_mockedFunctions_h_

#include <sys/types.h>
#include <stdint.h>
#include <iostream>
#include <unistd.h>

#include <test/mockFunctions.h>
namespace test
{
}


namespace MockedFunctions
{
  enum
  {
    close,
    read,
    write,
    rename,
    link,
    unlink,
    sleep,
    usleep,
    pipe,
    fork,
    execv,
    ioctl,
    rmdir,
    unlinkat,
    lastMockFunction = unlinkat
  };
}

namespace test
{
  using close = OneParameterFunction<MockedFunctions::close, int, int>;
  template <> inline const char* TestFunction<MockedFunctions::close>::name() const { return "close"; }
  template <> inline void setUpMock<MockedFunctions::close>() { close::setup(); }

  using read = ThreeParameterFunction<MockedFunctions::read, ssize_t, int, void*, size_t>;
  template <> inline const char* TestFunction<MockedFunctions::read>::name() const { return "read"; }
  template <> inline void setUpMock<MockedFunctions::read>() { read::setup(); }

  using write = ThreeParameterFunction<MockedFunctions::write, ssize_t, int, const void*, size_t>;
  template <> inline const char* TestFunction<MockedFunctions::write>::name() const { return "write"; }
  template <> inline void setUpMock<MockedFunctions::write>() { write::setup(); }

  using rename = TwoParameterFunction<MockedFunctions::rename, int, const char*, const char*>;
  template <> inline const char* TestFunction<MockedFunctions::rename>::name() const { return "rename"; }
  template <> inline void setUpMock<MockedFunctions::rename>() { rename::setup(); }

  using link = TwoParameterFunction<MockedFunctions::link, int, const char*, const char*>;
  template <> inline const char* TestFunction<MockedFunctions::link>::name() const { return "link"; }
  template <> inline void setUpMock<MockedFunctions::link>() { link::setup(); }

  using unlink = OneParameterFunction<MockedFunctions::unlink, int, const char*>;
  template <> inline const char* TestFunction<MockedFunctions::unlink>::name() const { return "unlink"; }
  template <> inline void setUpMock<MockedFunctions::unlink>() { unlink::setup(); }

  using sleep = OneParameterFunction<MockedFunctions::sleep, unsigned, unsigned>;
  template <> inline const char* TestFunction<MockedFunctions::sleep>::name() const { return "sleep"; }
  template <> inline void setUpMock<MockedFunctions::sleep>() { sleep::setup(); }

  using usleep = OneParameterFunction<MockedFunctions::usleep, int, useconds_t>;
  template <> inline const char* TestFunction<MockedFunctions::usleep>::name() const { return "usleep"; }
  template <> inline void setUpMock<MockedFunctions::usleep>() { usleep::setup(); }

  using pipe = OneParameterFunction<MockedFunctions::pipe, int, int*>;
  template <> inline const char* TestFunction<MockedFunctions::pipe>::name() const { return "pipe"; }
  template <> inline void setUpMock<MockedFunctions::pipe>() { pipe::setup(); }

  using fork = VoidParameterFunction<MockedFunctions::fork, pid_t>;
  template <> inline const char* TestFunction<MockedFunctions::fork>::name() const { return "fork"; }
  template <> inline void setUpMock<MockedFunctions::fork>() { fork::setup(); }

  using execv = TwoParameterFunction<MockedFunctions::execv, int, const char*, char* const*>;
  template <> inline const char* TestFunction<MockedFunctions::execv>::name() const { return "execv"; }
  template <> inline void setUpMock<MockedFunctions::execv>() { execv::setup(); }

  using ioctl = ThreeParameterFunction<MockedFunctions::ioctl, int, int, int, VaList>;
  template <> inline const char* TestFunction<MockedFunctions::ioctl>::name() const { return "ioctl"; }
  template <> inline void setUpMock<MockedFunctions::ioctl>() { ioctl::setup(); }

  using rmdir = OneParameterFunction<MockedFunctions::rmdir, int, const char*>;
  template <> inline const char* TestFunction<MockedFunctions::rmdir>::name() const { return "rmdir"; }
  template <> inline void setUpMock<MockedFunctions::rmdir>() { rmdir::setup(); }

  using unlinkat = ThreeParameterFunction<MockedFunctions::unlinkat, int, int, const char*, int>;
  template <> inline const char* TestFunction<MockedFunctions::unlinkat>::name() const { return "unlinkat"; }
  template <> inline void setUpMock<MockedFunctions::unlinkat>() { unlinkat::setup(); }

}

LAST_MOCK_FN(lastMockFunction)

#endif
